language: php

env:
  global:
    - APP_ENVIRONMENT=development_test
    - MAIN_DOMAIN=template.dev

php:
  - 7.1

before_script:
  - printf "\n" | pecl install imagick
  - composer self-update
  - composer install --prefer-dist

script:
  - composer check
